### ISSUE TITLE
ISSUE: box color needs to be custom

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#1]
Next image shows the following parameters:
Uplot  show_box = True  background_color = WHITE
plot.tick_params  tickcolor = BLACK  tickgrid = True
ucartesian  line_color = BLACK)

As we can seem the show_box has no effect because it is draw in white color, so it is not visible. If I invert the background_color and line_color, then I can see the box.

Please add a parameter for the box color.

![image](https://user-images.githubusercontent.com/147128/223489273-476c6703-9a5d-402c-8f5e-d3e2dfeeb64b.png)

**Comment by jposada202020** [comment]
Thanks for the comment :)

**Comment by jposada202020** [comment]
Hello I added box_color argument to the Uplot, I added the ability to add some customs colors.  If you want to try it. I have updated the https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_tickparameters.py example, and updated the Quick start guide https://github.com/jposada202020/CircuitPython_uplot/blob/main/docs/quick_start.rst.
![image](https://user-images.githubusercontent.com/34255413/223575090-298b9233-ef45-4f20-b265-382953253f31.png)

Thanks.

**Comment by casainho** [comment]
Works as expected. Thank you.
