### ISSUE TITLE
Need better scale description

### ISSUE THREAD

**Issue by DJDevon3** [jposada202020/CircuitPython_uplot#10]
In [read the docs](https://circuitpython-uplot.readthedocs.io/en/latest/) The description for scale is fairly vague. I imagine it works like label.label scale where 2 is a little bigger label?

```py
from circuitpython_uplot.uplot import Uplot, color
from circuitpython_uplot.ubar import ubar
plot = Uplot(0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT, box_color=color.BLACK, scale=100)

text_group = displayio.Group()
text_group.append(plot)
text_group.append(date_label)
text_group.append(time_label)
text_group.append(pulse_label)
display.show(text_group)

a = ["a", "b", "c", "d", "e"]
b = [ListValues[0], ListValues[1], ListValues[2], ListValues[3], ListValues[4]]
ubar(plot, a, b, 0xFF1000, True)
```
I saw no difference between scale=2 or scale=100.  Bit of head scratching as to what scale does.

![ubar_uplot](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/7ba79346-caae-4ea4-9a2d-774468342429)

**Comment by jposada202020** [comment]
Hello. Thanks. Going to take a look tomorrow. Need to refresh my memory. And I'll se what can be done to improve it. Thanks :)

**Comment by jposada202020** [comment]
@DJDevon3 I corrected the behaviour and add a new example here:
please take a look
https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_ubar_scale_example.py

**Comment by DJDevon3** [comment]
Thank you :)
