### ISSUE TITLE
ubar 4th refresh index out of range

### ISSUE THREAD

**Issue by DJDevon3** [jposada202020/CircuitPython_uplot#11]
Was happening every 3rd refresh. Updated to your latest ubar.py and uplot.py manually and now it happens every 4th refresh. As far as I can tell the bars are behaving oddly after each refresh.  

3 days ago with the previous commit the bars would overlay on top of each other and not remove.  

![ubar_overdraw](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/7f307a00-343f-4ab1-8b10-eac5a22d3e51)

Now they are actually removing but not redrawing correctly and leaving only the first bar, still with an out of range error.

![ubar_outofrange](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/58215d68-c41f-4950-bd46-ae28a502a17b)

```py
===============================
Connecting to WiFi...
Connected!


-----Token Refresh POST Attempt -------
Next Refresh Token:  a09998aacf19d15589e151d582ee111fe52e085dddef1ec46d1c12a5332ba3a4

Attempting to GET FITBIT Stats!
===============================
Fitbit Date: 2023-07-17
Fitbit Time: 13:29
Today's Logged Pulses : 808
Latest 5 Minute Averages: 92,95,110,110,100
Uplot List a: a,b,c,d,e
Uplot List b: 92,95,110,110,100
Board Uptime:  55 minutes

Finished!
Next Update in:  30 seconds
===============================

-----Token Refresh POST Attempt -------
Next Refresh Token:  b8962db79c118182fe4c96b7f694eb0dc6e20520d81ed6bfff107810895e6ccf

Attempting to GET FITBIT Stats!
===============================
Fitbit Date: 2023-07-17
Fitbit Time: 13:29
Today's Logged Pulses : 808
Latest 5 Minute Averages: 92,95,110,110,100
Uplot List a: a,b,c,d,e
Uplot List b: 92,95,110,110,100
Board Uptime:  56 minutes

Finished!
Next Update in:  30 seconds
===============================

-----Token Refresh POST Attempt -------
Next Refresh Token:  c44a8cebe53a8a8477b413fe9689a6b1c71b59e6b5c17e3a982d6d8d6c701abf

Attempting to GET FITBIT Stats!
===============================
Fitbit Date: 2023-07-17
Fitbit Time: 13:29
Today's Logged Pulses : 808
Latest 5 Minute Averages: 92,95,110,110,100
Uplot List a: a,b,c,d,e
Uplot List b: 92,95,110,110,100
Board Uptime:  56 minutes

Finished!
Next Update in:  30 seconds
===============================

-----Token Refresh POST Attempt -------
Next Refresh Token:  e8932d51e2b5c9577a85a4f475a4c1c360d62a17ffe1915e6e79b5edd4e3f2e0

Attempting to GET FITBIT Stats!
===============================
Fitbit Date: 2023-07-17
Fitbit Time: 13:29
Today's Logged Pulses : 808
Latest 5 Minute Averages: 92,95,110,110,100
Uplot List a: a,b,c,d,e
Uplot List b: 92,95,110,110,100
Index Error: index out of range

-----Token Refresh POST Attempt -------
Next Refresh Token:  3f6c8c3095816267b95258276d9510402e37c316ed10c44c452d06257b73a6cc

Attempting to GET FITBIT Stats!
===============================
Fitbit Date: 2023-07-17
Fitbit Time: 13:29
Today's Logged Pulses : 808
Latest 5 Minute Averages: 92,95,110,110,100
Uplot List a: a,b,c,d,e
Uplot List b: 92,95,110,110,100
Index Error: index out of range
```
```py
plot = Uplot(0, 0, DISPLAY_WIDTH, DISPLAY_HEIGHT, padding=10, background_color=color.BLACK, box_color=color.BLACK)
while True:
    a = ["a", "b", "c", "d", "e"]
    b = [activities_latest_heart_value4, activities_latest_heart_value3, activities_latest_heart_value2, activities_latest_heart_value1, activities_latest_heart_value0]
    print(f"Uplot List a: {a[0]},{a[1]},{a[2]},{a[3]},{a[4]}")
    print(f"Uplot List b: {b[0]},{b[1]},{b[2]},{b[3]},{b[4]}")
    try:
        ubar(plot, a, b, 0xFF1000, True)
    except (IndexError) as e:
        print("Index Error:", e)
        time.sleep(60)
        continue
```
Printing list a & b should show some kind of anomaly for the index value but I see no change in the list. It reliably produces an index out of range error every 4th attempt.

This is part of a larger adafruit_requests Fitbit example script. Attempted to get help via adafruit discord before creating an issue.
[Discord conversation with entire script.](https://discord.com/channels/327254708534116352/537365702651150357/1130529868719853638)

**Comment by DJDevon3** [comment]
It appears to be running out of colors as the color sequence is always the same.  Is there a way to have the bar graph color array loop so it doesn't run out?  That's just a guess.

**Comment by jposada202020** [comment]
Thank you, yes, that was the case.  Please see https://github.com/jposada202020/CircuitPython_uplot/releases/tag/0.11.2
just FYI according to my test you will run out of memory in the 49 refresh at least with 5 bars. The library could be modified to have a function to update the bars with a specific function a preserve memory, and run ideally forever, but will require more development. If you are happy to wait, I am happy to code it :)

**Comment by DJDevon3** [comment]
Definitely better. Been running it for about an hour every 30 seconds and haven't hit the limit yet.  I have noticed some odd artifacts though starting on the 3rd refresh with the first two bars either skipped or black.
```py
ubar(plot, a, b, 0xFF1000, True)
```

![skipping_or_black_graph](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/3c0b827c-c89f-4769-9f65-73b326dd84fb)

Then the next get request after that one I get this. 

![skipping_or_black_graph_overdraw](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/f3aedabf-bf3e-436a-9ee9-5d49da6fc453)

The cycle repeats itself infinitely so far every 3rd or 4th refresh after that with the black bars and red overdraw. The first bit of red overdraw is always present in every subsequent display. The other 4 bars are fine as far as I can tell.

**Comment by DJDevon3** [comment]
After about 2 hours becomes unrecognizable and not very useful to say the least. There's definitely some room for improvement.

![IMG_1082_2](https://github.com/jposada202020/CircuitPython_uplot/assets/49322231/57a2d53b-a626-499c-be3a-94b454e431fe)

**Comment by jposada202020** [comment]
Indeed, you are creating new barplot instances one on top of the other so this is expected, the library auto-scale the limits so sometimes previous bar are hidden and sometimes they are not. This will be the normal behaviour unless a new update function is created in the library to update the original bars. A hack, is to remove the bar from the group as in the following example:

```python
# SPDX-FileCopyrightText: Copyright (c) 2023 Jose D. Montoya, DJDevon
#
# SPDX-License-Identifier: MIT

import board
from circuitpython_uplot.uplot import Uplot, color
from circuitpython_uplot.ubar import ubar
import time

# Setting up the display
display = board.DISPLAY

# Configuring display dimensions
DISPLAY_WIDTH = 480
DISPLAY_HEIGHT = 320

# Defining the plot
plot = Uplot(
    0,
    0,
    DISPLAY_WIDTH,
    DISPLAY_HEIGHT,
    background_color=color.BLACK,
    padding=10,
    box_color=color.BLACK,
)

# Dummy data to plot
activities_latest_heart_value = [55, 20, 25, 30, 35, 10]
a = ["a", "b", "c", "d", "e", "f"]
number_of_bars = len(activities_latest_heart_value)


multiplier = 1
# Showing the plot
display.show(plot)

for i in range(20):
    activities_latest_heart_value_changed = [
        j + multiplier for j in activities_latest_heart_value
    ]
    ubar(
        plot,
        a,
        activities_latest_heart_value_changed,
        0xFF1000,
        True,
        color_palette=[
            0xFF1000,
            0x00FF00,
            0x0000FF,
            0xFFFF00,
            0x00FFFF,
            0x123456,
        ],
    )

    multiplier += 1
    time.sleep(1)
    for _ in range(number_of_bars):
        plot.pop()




```

**Comment by jposada202020** [comment]
Hiya, please take a look in[ 0.13.0 ](https://github.com/jposada202020/CircuitPython_uplot/releases/tag/0.13.0)including an updating function for filled bars.
