### ISSUE TITLE
Setting uplot padding to 0 doesnt behave as expected

### ISSUE THREAD

**Issue by tyeth** [jposada202020/CircuitPython_uplot#13]
I tried setting the height etc to 1 pixel less, but still same issue, it overflows the bottom right. Padding of 1px looks fine, but may have the padding overflowed past the drawable area on the right and bottom edges.
```
plot = Uplot(
    0,
    0,
    DISPLAY_WIDTH-1,
    DISPLAY_HEIGHT-1,
    background_color=color.BLACK,
    padding=0,
    box_color=color.WHITE,
)
```
Same code as the ubar max_value test

**Comment by jposada202020** [comment]
Hello, yes issue confirmed. Thanks :), must be some problem in the padding logic. I can use the full 240x135 size with padding 1. Ill take a look.

**Comment by jposada202020** [comment]
Forget to post the previous message :), I think this is fixed in https://github.com/jposada202020/CircuitPython_uplot/releases/tag/0.14.2. Thanks
