### ISSUE TITLE
Add a tickheight for x and tickheight for y

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#2]
As the description says: Add a tickheight for x and tickheight for y, while currently tickheight apply for both axis.

**Comment by jposada202020** [comment]
Will do Thanks :)

**Comment by jposada202020** [comment]
@casainho changes in 0.8.1. I had o modified the rc_parameters example again, so please use the one in the library. Thanks.

**Comment by casainho** [comment]
Works as expected. Thank you.
