### ISSUE TITLE
ISSUE: rangey issues

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#3]
This is without defining the rangey value:
![image](https://user-images.githubusercontent.com/147128/223778570-af23135c-1138-4764-9858-fe2931cdf3c0.png)

And here when I define the rangey:
![image](https://user-images.githubusercontent.com/147128/223778974-f02b89c7-5fce-4836-9c51-776e18249705.png)

The graph bellow for instance, I want to set the rangey to [0, 100] as it represents the humidity value. But I am setting this graph with a Y Uplot value range of 60 pixels... am I doing something wrong?? The code is here:

https://github.com/casainho/temperature_humidity_sensor_eink_display/blob/c55bfa4096d32b75d49c124ca4a59acf7a3b9640/firmware/main.py

**Comment by casainho** [comment]
I do not have that values. But basically, the first graph in temperature and the other humidity. The list of values on the graph are initial very few values with similar values as seen in text / numeric values. The rest of values are all '0'.

Why would the graph not show the line on the '0' values, when I define a rangey value?

**Comment by casainho** [comment]
I need to set rangy for first graph to [0 - 50] that is temperature and [0 - 100] that is humidity. How should I do it, can you please suggest and I will do it?

This is the graph with real values, but automatic Y range... on the last points / 30 minutes, I did open the door and so the temperature decreased and humidity increased, that is correct:

![image](https://user-images.githubusercontent.com/147128/223824641-dc99c95a-9077-41e6-b7fd-97edf965324d.png)

**Comment by jposada202020** [comment]
BTW, this is hack, Library was not intended to dynamic data, maybe you could use the sparkline shapes library, I have just an example here https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_sparkline.py or the original one in the library https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes/blob/main/adafruit_display_shapes/sparkline.py.

**Comment by jposada202020** [comment]
@casainho made some changes, take a look at the example here https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_ucartesian_loggin_data.py

result: https://github.com/jposada202020/CircuitPython_uplot/blob/main/docs/uplot_cartesian.gif


Changes are in 0.8.2. Thanks
