### ISSUE TITLE
Please add number of tickx and ticky

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#6]
I wish to be able to define the numbers of ticks. For instance, my graph x represents the time, in hours and will be the total of 24h. So maybe I will want 3 tickx, one for each 8 hours, or 6 tickx, one for each 4 hours. Similar concept for the ticky.

**Comment by jposada202020** [comment]
Yes, please see my answer for #5. This will require, work on ticks definitions. As other submodules depend on a `standard` definition, the best solution I think is to create another submodule called logging where the user can change the ticks as you described. thanks

**Comment by jposada202020** [comment]
Please see 0.9.0. thanks :) and the example https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_ulogging.py

**Comment by casainho** [comment]
Works well as expected, thanks!!

Here is an image (values on the graphs are simulated):

![image](https://user-images.githubusercontent.com/147128/224314397-d93409eb-c070-4967-bee2-0b906cfa5e0e.png)

**Comment by jposada202020** [comment]
I love it :)

**Comment by casainho** [comment]
> I love it :)

Thanks!! And many thanks to you too!!

It is pretty much finished. I just want try to use a graphic element for temperature (🌡️) and a drop 💧 for humidity, to replace the °C and %.

I also would like to try fill the graph, but that option is not available on the ulogging...

Also, I wish to try the ticks with some padding to be outside of the box, because with fill graph, the thicks will disappear...

**Comment by jposada202020** [comment]
The ticks placement is something that we could work on, not difficult to implement. So ill work on that. I would recommend for the symbols use a customize font, to include the symbols, I could create one font and put it in the project. For an example of such a font take a look here https://github.com/jposada202020/circuitpython_knitting, There are free .svg symbols available so we could include them easily in a font. 
Could you be more specific about fill the graph?, under the graph?. cheers. let me know

**Comment by casainho** [comment]
1. Thanks for the ticks placement.
2. About the icons on a font, yes, please do that!! and then I will use that font. Your repository should have some image on the README.md, or at least for persons like me that I am more visual, otherwise only text is boring.
3. If you can get that two symbols on your font, that would be great. I am looking for similar symbols as on the IKEA VINDSTYRKA sensor - image bellow.
4. About fill, I mean that ucartesian have the fill=True while the ulogging do not have that option, can you please add it?

![image](https://user-images.githubusercontent.com/147128/224368850-b6815afb-54b2-4eb0-ab7f-cbac82a009dc.png)

**Comment by jposada202020** [comment]
No worries, ill work on that over the weekend, in the meantime I just uploaded the font, so you could use it and you could use this example script. Just put the font in the examples' folder in the library, in a font directory in your board. Or you could also change the location.

``` python


import board
from adafruit_display_text import label
from adafruit_bitmap_font import bitmap_font


display = board.DISPLAY

font_file = "fonts/forkawesome-36.pcf"

# Set text, font, and color
text = "{}  {}  {}  {}".format("\uf2c7", "\uf2c9", "\uf2ca", "\uf043")
font = bitmap_font.load_font(font_file)
color = 0xFFFFFF

# Create the tet label
text_area = label.Label(font, text=text, color=color)

# Set the location
text_area.anchor_point = (0.5, 0.5)
text_area.anchored_position = (display.width // 2, display.height // 2)

# Show it
display.show(text_area)

while True:
    pass

```

**Comment by jposada202020** [comment]
for the ticks placement, 
now you could have it

```python

ulogging(
    plot_1,
    x,
    temp_y,
    rangex=[0, 200],
    rangey=[0, 50],
    line_color=color.BLACK,
    ticksx=[10, 50, 80, 100],
    ticksy=[15, 30, 45, 60],
    tick_pos=True,
    fill=True,
)
```

**Comment by casainho** [comment]
Thanks and here is what I see:
- I can not control the ticks size with this option
- I do not see the ticks on the X axis

![image](https://user-images.githubusercontent.com/147128/225088541-26d91d21-b9ee-4062-a4cf-cc6ce7a83ab4.png)

**Comment by jposada202020** [comment]
That is interesting. will take a look later this week
