### ISSUE TITLE
Release zip file without the compiled python files

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#8]
I would say it is not supposed for this zip file to be "empty", with only the examples folder:
![image](https://user-images.githubusercontent.com/147128/224289388-af761139-92be-4d0b-81d9-e147d94426d6.png)

**Comment by jposada202020** [comment]
That is indeed not good, normally. Thanks for checking ill take a look

**Comment by jposada202020** [comment]
could not find the reason for this, maybe is some setup in the library, but I submitted an issue in the community library. In the meantime, installing via circup is working fine, so I would recommend doing so, is much much easier :)

**Comment by jposada202020** [comment]
this could be a fix https://github.com/adafruit/workflows-circuitpython-libs/pull/16

**Comment by jposada202020** [comment]
solved in 0.10.2
