### ISSUE TITLE
IDEA: fill with a mesh on white and black EInk displays 

### ISSUE THREAD

**Issue by casainho** [jposada202020/CircuitPython_uplot#9]
My screen have a good pixel density. I really like EInk feeling for this appication.

I wish to have the graph fill option enabled, but then the blacks are to much strong. Please add a mesh fill option, so it will be like gray, with pixel on, pixel off, pixel on, pixel off and so on.

![20230311_112156~2](https://user-images.githubusercontent.com/147128/224500809-08beedf7-5fbe-44f8-a657-2cfb0369760a.jpg)

**Comment by jposada202020** [comment]
There you go.. see the example https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_logging_fill.py

**Comment by jposada202020** [comment]
@casainho Let me know If I could use this picture in the readme as an example. Thanks :)

**Comment by casainho** [comment]
Yes, use any picture you want. In a few days I hope to close the project and probably have better pictures and the graphs full o data.

**Comment by casainho** [comment]
Not exactly what I was expecting but the result is good!

Seems there are small little issues:

- first white line is always divided in 3 lines(??)
- the white lines not always go to near the max value of that line.

**Comment by jposada202020** [comment]
I think those are artifacts, aka, not intended but present. The lines are drawn from each point to the axes, so if the X axis, so maybe the next temp/hum point is not in the next vertical line. As you could see in the Scale example. Thanks

**Comment by casainho** [comment]
The graphs are really great, as you can see.

I have an issue, that after 24h, the graph values are not updated for some reason, but after some time (hours?? a day??) it updates and seems to then update every 10 minutes as it is programmed.

That little number on the second picture, 442, is 442 * 10 minutes, is about 3 days and some hours. I am testing the batteries to see for how long they last:

![image](https://user-images.githubusercontent.com/147128/226201014-d8047900-afbc-4022-abad-33bb0426f20b.png)

![image](https://user-images.githubusercontent.com/147128/226201041-a999e19a-9a6a-4819-85f2-425085fdb3da.png)

**Comment by jposada202020** [comment]
Amazing. I  love it
